working on table and pagination
hemavmane/COVID-APP-GROUP-R1 pull request #5
Opened 2022-11-11 12:18 UTC by GAYATRIBHAGWAT11

working on table and pagination

2022-11-12 16:49 UTC, Souvikdeb2612 requested changes

2022-11-12 16:49 UTC, Souvikdeb2612 commented on src/Component/ContextApi/ContextApi.js
> +        `https://vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com/api/npm-covid-data/`,
store url separately in a variable/state and use wherever required

2022-11-12 16:49 UTC, Souvikdeb2612 commented on src/Component/CovidGraph/CovidGraph.jsx
> +import "react-toastify/dist/ReactToastify.css";
First external imports occur that is imports from installed libraries, then 1 line space, then all internal imports that is files/components/functions that you have created, then 1 line space and then finally all css imports.

2022-11-23 05:02 UTC, Souvikdeb2612 requested changes

2022-11-23 05:02 UTC, Souvikdeb2612 commented on src/Component/DataTable/Posts.jsx
> +                        {posts.map(post => {
destructure post here

2022-11-23 10:37 UTC, GAYATRIBHAGWAT11 commented
final changes and registration form updated

2022-11-27 08:44 UTC, GAYATRIBHAGWAT11 commented
changing reviewer to hema

2022-11-27 09:40 UTC, merged