Gayatri
hemavmane/COVID-APP-GROUP-R1 pull request #8
Opened 2022-11-12 16:24 UTC by GAYATRIBHAGWAT11

data table is completed

2022-11-12 17:05 UTC, Souvikdeb2612 requested changes

2022-11-12 17:05 UTC, Souvikdeb2612 commented on src/Component/DataTable/DataTable.jsx
> +import Posts from "../DataTable/Posts";
First external imports occur that is imports from installed libraries, then 1 line space, then all internal imports that is files/components/functions that you have created, then 1 line space and then finally all css imports.

2022-11-12 17:05 UTC, Souvikdeb2612 commented on src/Component/DataTable/DataTable.jsx
> +                'https://vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com/api/npm-covid-data/',
store url externally in a state/variable and use wherever required

2022-11-12 17:05 UTC, Souvikdeb2612 commented on src/Component/DataTable/DataTable.jsx
> +                console.error(err);
remove console statements before raising pr

2022-11-12 17:05 UTC, Souvikdeb2612 commented on src/Component/DataTable/DataTable.jsx
> +                console.log(res.data);
remove console statements before raising pr

2022-11-12 17:05 UTC, Souvikdeb2612 commented on src/Component/DataTable/DataTable.jsx
> +                            <button className="btn" onClick={handleNextBtn} disabled={currentPage == pages[pages.length - 1] ? true : false}>Next</button>
create a function for the disabled feature and call the function here

2022-11-12 17:05 UTC, Souvikdeb2612 commented on src/Component/DataTable/DataTable.jsx
> +                            <button className="btn" onClick={handlePrevBtn} disabled={currentPage == pages[0] ? true : false}>Prev</button>
create a function for the disabled feature and call the function here

2022-11-12 17:05 UTC, Souvikdeb2612 commented on src/Component/DataTable/Posts.jsx
> +import '/Users/admin/CovidAppProject/COVID-APP-GROUP-R1/src/Component/DataTable/Posts.css'
add 1 line space before css imports

2022-11-12 17:05 UTC, Souvikdeb2612 commented on src/Component/DataTable/Posts.jsx
> +                        {posts.map(post => {
destructure post above

2022-11-12 17:05 UTC, Souvikdeb2612 commented on src/Component/DataTable/Posts.jsx
> +                                <td>{post.TotalRecovered}</td>
total recovered is coming twice

2022-11-12 17:05 UTC, Souvikdeb2612 commented on src/Component/DataTable/Posts.jsx
> +                            <th>Country</th>
This is constant data so export from constant folder

2022-11-15 10:31 UTC, GAYATRIBHAGWAT11 commented
changes resolved

2022-11-15 10:32 UTC, GAYATRIBHAGWAT11 reviewed
resolved changes

2022-11-22 17:27 UTC, GAYATRIBHAGWAT11 commented
registration form completed

2022-11-27 09:39 UTC, merged